### PR TITLE
speed button for android

### PR DESCRIPTION
**Pull request by colonelfazackerley**
This pull request has a delicious gooey centre.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
poo

rabbit-escape-ui-android.iml probably should not be here

**Comment by andybalaam** [comment]
```
git reset HEAD^
git add files not including .iml
git commit
```

**Comment by colonelfazackerley** [comment]
done

**Comment by andybalaam** [comment]
Android developer. CV++

**Comment by andybalaam** [comment]
On my phone there is quite a bit of space around the speed up button. Given that on many devices vertical space is at a premium (because we want all token button visible whenever possible) I think I'd argue it should be close to mute and pause.

**Comment by colonelfazackerley** [comment]
I have no idea why there is a bit more space.

**Comment by andybalaam** [comment]
Ok I'll take a look when I get a chance. 

Also: it looks really cool! Speed up button works and void works.

**Comment by andybalaam** [comment]
Fixed the spacing issue in 05a6d1cbf1fd3e54ccd210fdb91e1e0c795de815

**Pull request merged**
