### PR TITLE
Dont pull this one!

### PR DESCRIPTION
**Pull request by colonelfazackerley**
just put this up so the android studio project file fighting may be easily visualised.

### CODE REVIEW

**Comment by andybalaam** [comment]
If you revert all the idea files to their previous state (with idea closed) then start idea how much gets updated?

**Comment by colonelfazackerley** [comment]
One file is changed. The unfortunate side effect is that the code wont compile anymore. I then closed the project, and re-opened. Some time consuming things happen and then the project works again. Now loads of the files are changed again.

**Comment by colonelfazackerley** [comment]
maybe we can gitignore everything here and then very tentatively bring the odd file back in.

the git pain from this is much worse than the pleasure from shared code formatting and warning settings.

**Comment by andybalaam** [comment]
Yes and code formatting pain can be fixed with command line tools but what I do care about is how easy it is to get started from a clean environment.

**Comment by andybalaam** [comment]
Let's track this in #318

**Pull request closed without merging**
