### PR TITLE
initial doxygen config

### PR DESCRIPTION
**Pull request by colonelfazackerley**
result can be seen here

http://www.extant.plus.com/rabbit_doxy/index.html

### CODE REVIEW

**Comment by andybalaam** [comment]
Not convinced the graphs add much.  What do you think?

**Comment by andybalaam** [comment]
Shall I host the generated docs somewhere on artificialworlds?

**Comment by colonelfazackerley** [comment]
I like the graphs. Probably becuase I am struggling to remember how Java OOP works. I think it's possible to tweak the config so it does not generate so many.

On your site would be best. I would happy to help with keeping that up to date, if I can.

**Comment by andybalaam** [comment]
Cool, if they're helpful, they can stay.  I'll make a Makefile target to push them to my site and do it when I remember.  If we need to automate it some day, we can.

**Comment by andybalaam** [comment]
It's here http://artificialworlds.net/rabbit-escape/doxygen/ - let me know if it's not ok.

**Comment by colonelfazackerley** [comment]
I wrote this to push to my ISP. My ISP only has a rather naff service, ftp upload only.

```
#!/bin/bash    
HOST="ftp.plus.net"
USER="extant"
echo -n "Password for $USER:" 
read -s PASSWORD
FTPURL="ftp://$USER:$PASSWORD@$HOST"
LCD="./doc/html/"
RCD="/htdocs/rabbit_doxy"
DELETE="--delete"
lftp -c "set ftp:list-options -a;
open '$FTPURL';
lcd $LCD;
cd $RCD;
mirror --reverse \
       $DELETE \
       --verbose "

```
I excluded it from the pull request, as having so much config specific to me didn't seem right.

**Comment by andybalaam** [comment]
See the target doxygen-upload I put in the Makefile for my equivalent.  Hopefully not too noisy although it clearly can only be run by me.

**Comment by colonelfazackerley** [comment]
The link you put in INSTALL.md works.

rsync is much nicer than what I did. I could not use it for this, as SSH is needed on the server end, I think.

**Comment by andybalaam** [comment]
Yes, rsync uses ssh by default, which does require a server.

**Pull request merged**
