### PR TITLE
list playable levels with runrabbit

### PR DESCRIPTION
**Pull request by colonelfazackerley**

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I have this in my .bashrc
```bash
# tab completion for runrabbit
complete -W swing -o dirnames -o filenames runrabbit
```
With this PR I think it should be possible to get level names tab completing, though I have not quite got there yet.

**Comment by colonelfazackerley** [comment]
or maybe ALT+/ completing, which is OK.

**Comment by andybalaam** [comment]
That would be very cool

**Comment by colonelfazackerley** [comment]
I did try to get this tab completing, but failed. I find the bash command "complete" to be poorly documented.

**Comment by andybalaam** [comment]
I made an issue to remind me too look at it

**Pull request merged**
