### PR TITLE
swing solution player

### PR DESCRIPTION
**Pull request by colonelfazackerley**
I put this up so progress can be tracked.

Let me know if the class should be renamed SolutionPlayer.

early feedback is valued.

### CODE REVIEW

**Comment by andybalaam** [comment]
On naming I appreciate the desire to avoid sticking words together but think Player is very generic. How about Playback?

**Comment by andybalaam** [comment]
Most of the logic you've written I think is a duplicate of SolutionRunner - that takes in a Solution and provides an iterator through time steps. That is exactly what you need I think. (And was at the root of why I wanted to refactor the solution stuff I did.

**Comment by colonelfazackerley** [comment]
I can't see how to re-use that code. SolutionRunner seems to need to have it's own copy of the world in a sandbox game. It wants to step the world. For playback in the realtime UIs, I think the realtime UI has to step the world.

Most of it's methods are private: nothing for swing to call to find out what actions to take. 

So, I am going to need some pointers on how to get started with using SolutionRunner for this purpose.

**Comment by colonelfazackerley** [comment]
I create a SandBox game which clones the world used by swing. I then use SolutionRunner.runPartialSolution one command at a time? I can't see a way SolutionRunner is going to tell me for a particular timestep what token selections and drops to make (without more - possibly fiddly - code)

**Comment by andybalaam** [comment]
Ah sorry not SolutionRunner, SolutionInterpreter.

**Comment by andybalaam** [comment]
If it doesn't make sense let's have a chat or Skype about it. It may not for add well as I hoped it would

**Comment by colonelfazackerley** [comment]
SolutionInterpreter makes a lot of sense.

Those ignorant* of the codebase are doomed to attempt to recode it.

Should SolutionRunner move to text?

*me

**Comment by colonelfazackerley** [comment]
Ah, SolutionRunner is used by tests so it belongs in engine.

i think I will kill this branch, and try again in a new pull request.

**Comment by andybalaam** [comment]
Sorry I know my communication around that whole refactoring was horrible. I am glad this has led us to clear it up a bit. When you start to use it hopefully you can recommend how to make it easier to understand too.

**Comment by colonelfazackerley** [comment]
I was probably just being dense. SolutionInterpreter is clear. Naming is tricky. They could probably all do with a little doxygen to explain the difference between runner and interpreter, etc.

**Comment by andybalaam** [comment]
Yes

**Pull request closed without merging**
