### PR TITLE
Five levels which demonstrate various aspects of water.

### PR DESCRIPTION
**Pull request by tttppp**
This contains the five levels created as part of the water feature. The issue numbers are #359, #360, #361, #362 and #363.

### CODE REVIEW

**Comment by andybalaam** [comment]
Very much looking forward to playing them

**Comment by colonelfazackerley** [comment]
I got 10 out in Fiery finish

8&'X'=y%i&=8^i&=8'o^%&=Egzcd'X'z=X')Ha%cAz]-=`Xy&y)'od'H'cy=yX{-)*A&7`''z^g&'X')'=yEgz'XAi&'X']&)`'X'%&q-'7=g'-a0^d`c&AyXzz8--E``'=)&cq&XX=g*'&0''8X)='di=oX'Hg''&8'Xi=)dc{'X'HyAE&-=']'^'i'=`)c'qX'7yo*)&0'X'^HE'U'='=8Ay'oXyAy&&&=`''')=X{a

**Comment by andybalaam** [comment]
I think your comment got corrupted by the markdown. Hopefully surrounding with triple back ticks should work.

**Comment by tttppp** [comment]
It looks like the original solution for Fiery Finish also gets out 10. I'm not sure why I made the target 8, but maybe as a distraction? Maybe I just typed the wrong number?!

**Pull request merged**
