### PR TITLE
Test anim

### PR DESCRIPTION
**Pull request by colonelfazackerley**

### CODE REVIEW

**Comment by andybalaam** [comment]
Yes, very good, thanks.  Some whitespace needs fixing btw.

**Comment by andybalaam** [comment]
btw do you hate the changes I have been making to make the build quieter?  I wish it could be verbose when it failed and quiet when it succeeded.

**Comment by colonelfazackerley** [comment]
I mostly prefer it. when it fails, I can't see why, though. I mostly use 'make test', and when it fails I can now do 'make test-verbose'

**Comment by andybalaam** [comment]
I guess we have to live with that until we find something better

**Pull request merged**
