### PR TITLE
Text oob bridge 2

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not working. seemingly unrelated things are failing tests. hoping someone can tell me why.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
something that I have done to Chars.java is breaking All_levels_load_and_round_trip

**Comment by colonelfazackerley** [comment]
Stupid mistake. I think I have it.

**Comment by colonelfazackerley** [comment]
Stupidity rebased away. Please merge now.

**Comment by andybalaam** [comment]
Great.

**Comment by colonelfazackerley** [comment]
Would it have been terrible to catch and ignore the OutOfBoundsException instead of checking bounds in the code? the JVM does bounds checking anyway...

**Comment by andybalaam** [comment]
It would have been good Python style.  In Java we normally avoid this, but not necessarily for good reasons.  In C++ throwing exceptions is significantly slower than normal operations, because/hence exceptions are considered only to be used in exceptional circumstances.

Personally I find the syntax of exceptions (in Java) horrible, so I try to avoid them where possible, using them only to bail out through several levels of code because something went wrong.

**Pull request merged**
