### PR TITLE
Refactor Direction as an enum.

### PR DESCRIPTION
**Pull request by tttppp**
I plan to add HERE as a "direction" (without an opposite). This also makes reading error messages in tests easier, as UP.toString() is now "UP" rather than "Direction@1234blah".

### CODE REVIEW

**Comment by andybalaam** [comment]
A few points:
1. This looks obviously better leading me to wonder why I didn't do it before. It may be just me being an idiot, but it may be because it isn't supported on the Android version we are using. 
2. If you need an enum that contains a new direction I suggest creating a new one rather than expanding this one, unless all the existing uses of this one are going

**Comment by andybalaam** [comment]
Sorry, closed accidentally.

**Comment by andybalaam** [comment]
Maybe I didn't realise you could put a function in an enum. I will check it works in Android and merge if it does.

**Comment by andybalaam** [comment]
This works fine on Android API level 8.  I guess I thought you couldn't have methods in enums, or was having some other kind of brain problem.

**Comment by andybalaam** [comment]
Point 2 above still applies I think.  It's not expensive to introduce a new enum if you want a different list of values.

**Comment by colonelfazackerley** [comment]
please could Direction.xOffset (and y) be ```public final``` instead of ```private ``` changeable.

**Comment by tttppp** [comment]
Thanks for the suggestions. My Water branch now has CellularDirection including HERE, and this is kept as is.  I've also changed to use public final constants.

**Comment by andybalaam** [comment]
Awesome

**Pull request merged**
