### PR TITLE
Arcade2

### PR DESCRIPTION
**Pull request by colonelfazackerley**
This is OK now
- all hints
- desc
- solutions
- ordered
- authors
- "make test" is good.

feedback necessary. 

i don't mind if you feedback to me, and i push some changes to this branch, or you merge this now, and tweak stuff yourself.

### CODE REVIEW

**Comment by andybalaam** [comment]
I am playing through slowly and will give feedback. Thanks for all the work.

**Comment by andybalaam** [comment]
I will build a snapshot based on latest when I get a chance.

**Comment by colonelfazackerley** [comment]
Cool. you can still re-order and tweak after merging, if you need.

**Comment by andybalaam** [comment]
I will continue giving feedback in #88 but you've done all the running on this set so I'm inclined to use the order you suggest.

**Pull request merged**
