### PR TITLE
Swing framedump for solution playback

### PR DESCRIPTION
**Pull request by colonelfazackerley**
This is slow. On my debian VM its not possible to play and dump frames. Also creating the gif after is slow, even for ImageMagick, so trying to do it in java may not be sensible.

These things may be tractable if the resolution is dropped for the dumped frames.

I think this is useful as it is: it allows the creation of high quality video.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
Here's one I made. It's close to the size limit that github allows.
anim

**Comment by colonelfazackerley** [comment]
A frame that I captured. This level probably isn't any use, unless you fancy something similar for a banner on artificalworlds.
frame_0000098

**Comment by andybalaam** [comment]
I like that frame. We should put it on the home page and play store page.

**Comment by andybalaam** [comment]
I feel sure we can compress them a lot. Maybe convert has options.

**Comment by colonelfazackerley** [comment]
I will work on the banner name level. Try to get a rabbit somewhere doing each activity.

**Comment by colonelfazackerley** [comment]
Just remembered. I need to update the help output.

**Comment by andybalaam** [comment]
Things I'd like to offer: gif bug reports,  tweet the last few seconds (for bragging about victories), visualise unit test failure.

**Comment by andybalaam** [comment]
Animated gif code http://elliot.kroo.net/software/java/GifSequenceWriter/ . Usual license caution applies,  and we would need to check it works with the old version of javs we use.

**Pull request merged**
