### PR TITLE
Wrap hints and descriptions automatically

### LINKED ISSUE #101: Avoid manual wrapping of descriptions and hints
Manually entering \n in the strings is a hassle. We could
1. Get the code displaying the dialog to figure out how long the lines should be, or,
2. Use a script or something to put the \n chars into the files.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
closes #101 

It's nice seeing the lines all the same length in the description and hints. Should make writing the levels less painful.

### CODE REVIEW

**Comment by andybalaam** [comment]
How will this affect Android?

**Comment by andybalaam** [comment]
Longer term,  we should use HTML style labels on Android and Swing,  but I'm happy to go with this for now.

**Comment by colonelfazackerley** [comment]
- I am assuming its "Tannhäuser" that's the ASCII issue. I will change that for a normal 'a'.
- I will look into Util.join
- I will look at Android, but I have not enabled non-play stuff, so I have no idea how to test it.
- re: HTML. The desc is HTML and the hints are not. I think that is your half-job :-p

**Comment by andybalaam** [comment]
Yes, sorry I did mean the ä. Yes, I did do half a job on HTML dialogs.

**Comment by andybalaam** [comment]
To build+debug you need "dev mode" not just untrusted apps.

**Comment by colonelfazackerley** [comment]
is there a VM platform I can use for android? even if its just a GUI?

I will push the ASCII and join thingies in a mo.

**Comment by colonelfazackerley** [comment]
from INSTALL

"There are Eclipse project files, so "File" -> "Import" -> "Existing projects into workspace" should work. Avoid the rabbit-escape-ui-android directory."

do you just edit the android code in a text editor outside the an IDE?

**Comment by andybalaam** [comment]
See the section in that file entitled "Android".  You will need Android Studio https://developer.android.com/sdk/index.html .  If you use a real Android device on Linux, you will need to do the udev magic here: https://developer.android.com/tools/device.html . Alternatively you can install an emulator from inside Android Studio, using the AVD Manager tool.

**Comment by andybalaam** [comment]
Setting up is somewhat complicated - the instructions I linked to are good, but long.

**Comment by andybalaam** [comment]
By VM platform did you mean similar to an emulator? If not I don't think I understand.

**Comment by colonelfazackerley** [comment]
yes, an emulator.

if I do put the package on my phone, what are the dependencies of "make android-debug"?

**Comment by colonelfazackerley** [comment]
I think it would work on android without any changes. I did just push a commit that removes the code that swaps \n for space. Perhaps you could test it? I will have a go, but I would not like to guess how long it will take me to get something working.

**Comment by andybalaam** [comment]
Yeah I'm happy to try it. I forgot we ignored newlines on Android. It should be fine.

**Comment by andybalaam** [comment]
If you follow the instructions on the Android site about how to install Android Studio, `make android-debug` should work.  That builds the package.  To run the package on my phone I usually click the Run button on Android Studio.

To enable developer mode, you don't need a package - just to press the right combination of keys: http://www.androidcentral.com/how-enable-developer-settings-android-42

**Comment by andybalaam** [comment]
Works perfectly on Android.  Nice change, thanks.

**Pull request merged**
