### PR TITLE
Rabbot level: Big Brother.

### PR DESCRIPTION
**Pull request by tttppp**
I didn't check out all the existing rabbot levels, so apologies if you've already made something similar!

Enjoy :-D

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
16 attempts. 40 mins. have not managed yet.

**Comment by tttppp** [comment]
It might be a little bit unfair. It's definitely possible, but maybe I should work on it a bit more. I had to add some blocks to prevent the easy solutions working, and one of them should probably block my 'correct' answer.

**Comment by colonelfazackerley** [comment]
I hadn't given up quite yet!

**Comment by tttppp** [comment]
Oops, I clicked the wrong button!

**Comment by tttppp** [comment]
Referencing #520

**Comment by andybalaam** [comment]
Great level, haven't solved it yet.

**Comment by andybalaam** [comment]
Ah, did it on about the 10th go, using extensive unsatisfying bridge stacking

**Comment by andybalaam** [comment]
Will post a solution when on pc

**Comment by andybalaam** [comment]
Released in 0.11

**Pull request merged**
