### PR TITLE
Fall and walk past exit

### PR DESCRIPTION
**Pull request by colonelfazackerley**
I forgot to add the fix # in the commit message.

### CODE REVIEW

**Comment by andybalaam** [comment]
Yes, in retrospect this is much better.
I think there is already a method somewhere in test code to step a world several times. I'd prefer to use that rather than add a method to World that is only used in tests.

**Comment by colonelfazackerley** [comment]
i will try and find that other method this evening.

**Comment by colonelfazackerley** [comment]
there is TestEntrance.fiveSteps()

but I think mine is better...

**Comment by colonelfazackerley** [comment]
WorldAssertions.assertWorldEvolvesLike()

looks better. I will look into it.

**Comment by andybalaam** [comment]
Yes I like that. It forces you to show all steps, which I basically like, but could probably be persuaded to allow skipping steps.

**Pull request merged**
