### PR TITLE
Remove text arg from ./runrabbit (now it's the default)

### PR DESCRIPTION
**Pull request by colonelfazackerley**
and some expect tests.

I have not done expect tests for things that produce or change files ("--encode foo.rel" etc. I could not decide how best to tidy up the temp files that result, or where to put them while the test runs)

I still need to change the .bat

Comments so far gratefully received.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I tested the bat. Note that windows %* does not need quotes like $@ for bash. It works for paths with spaces.

I think this is ready.

**Comment by colonelfazackerley** [comment]
I could not get ```--encode <string>``` to work with expect because of the funny characters produced. I could not find how to quote or escape them so it worked.

**Comment by colonelfazackerley** [comment]
I will do the wiki thing about comments after this. I wanted to mention the command line parameters in that article, as that's what moves the comments around.

**Comment by andybalaam** [comment]
Nice work.

**Pull request merged**
