### PR TITLE
dying on slopes continued

### PR DESCRIPTION
**Pull request by colonelfazackerley**
I set this up so you can see progress. (not ready yet)

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
now I have most of the rabbit melting away, then the head rolls down the hill and one of the eyes comes out.

mwahahahaha

(needs integrating into the game, but looks ok in AT)

**Comment by colonelfazackerley** [comment]
now I am back to where I thought I was.

**Comment by colonelfazackerley** [comment]
all the frames are done now. just need 2 more rea files for falling even numbers. integrate that into states. fix tests.

on left slopes the head starts rolling and one of the ears flies off.

**Comment by colonelfazackerley** [comment]
ready to be pulled!

**Comment by colonelfazackerley** [comment]
slope-splat

**Comment by andybalaam** [comment]
Beautiful! One thing to check: I thought I noticed some of the lines getting thin (probably where you shrunk shapes). I often find I have to adjust line widths after shrinking shapes. Normally all lines should be the same width no matter what size the shape is.

**Comment by colonelfazackerley** [comment]
I noticed that. I thought it was OK in the case of a death animation. Various body parts need to disappear. Having the lines thin down helps them to shrink to nothing gradually.

**Comment by andybalaam** [comment]
I'll look when I can get on a computer, but I am likely not to like it since it breaks the cartoon style.

**Comment by andybalaam** [comment]
Fading out has been used before,  which looks ok.

**Comment by colonelfazackerley** [comment]
OK. I might try thickening up the lines, but fading them.

**Pull request merged**
