### PR TITLE
use level names in menus

### PR DESCRIPTION
**Pull request by colonelfazackerley**
checked on swing, text and droid

this will conflict with #418. please merge that one first, and I will resolve the merge.

### CODE REVIEW

**Comment by tttppp** [comment]
This will be really useful for once the levels are completed and you want to go back to find a previous one. Also if the cheat is used and all levels are unlocked.

**Comment by colonelfazackerley** [comment]
Yeah, for the dev levels on droids, I think something like this is essential.

**Comment by andybalaam** [comment]
Yeah I was totally getting around to this - Thanks!

**Comment by colonelfazackerley** [comment]
It was almost done.

**Comment by andybalaam** [comment]
Ready to merge when rebased

**Comment by colonelfazackerley** [comment]
ready

**Pull request merged**
