### PR TITLE
test for blockers when bridging. fixes #58

### LINKED ISSUE #58: You can bridge through a blocker
If you place a bridge token next to an existing blocker, the rabbit that picks it up happily bridges right through the blocker.  Later rabbits don't climb up the bridge, but turn around as normal.

The first rabbit should refuse to pick up the bridge token (and possibly bridge the other way after turning around).

### PR DESCRIPTION
**Pull request by colonelfazackerley**

### CODE REVIEW

**Comment by andybalaam** [comment]
Needs rebasing but will merge when that's done. Nice fix, thanks.

**Comment by colonelfazackerley** [comment]
It's one clean commit. Do you mean I need to sync the branch with upstream, and then rebase?

**Comment by andybalaam** [comment]
Yes please - I can't merge until you do that.

**Comment by colonelfazackerley** [comment]
merged in the upstream changes. I have spent an hour and a half trying to rebase away the merge commit, but it will not die.

**Comment by andybalaam** [comment]
Thanks, merged.

**Pull request merged**
