### PR TITLE
Animations for climbing into exit

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not ready yet. just posting this for notification.

climbing right and exiting anim looks ok. not in game yet.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
Correction: it does work in the game, and 'make test' is good too.

Just need the climb left version.

**Comment by andybalaam** [comment]
Cool! If you can post gifs when it's ready that would be great.

**Comment by colonelfazackerley** [comment]
I think it's ready now.
exit-climb

**Comment by andybalaam** [comment]
Awesome

**Pull request merged**
