### PR TITLE
fixes #100 rabbits do not consume tokens while splatting.

### LINKED ISSUE #100: Bug: splat from height consumes token
```
r  
#  
   
   
   
 i 
###
```
This rabbit should not consume the bridge token as they die.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
fixes #100.

### CODE REVIEW

**Comment by andybalaam** [comment]
I think you can ask the falling behaviour whether it's been triggered to find out whether the rabbit is falling. I need to think about this a bit more - it seems weird. Couldn't we just ask whether it's falling to death based on its state and that should be enough?

**Comment by colonelfazackerley** [comment]
"Couldn't we just ask whether it's falling to death based on its state and that should be enough?"
No, that does not work. It's the first thing I tried. I think the reason it does not work, is to do with falling 2 squares per time step.

 "I think you can ask the falling behaviour whether it's been triggered to find out whether the rabbit is falling"
I will look at that. It's still tricky to get at the rabbit's Falling instance inside the behaviours List.

**Comment by colonelfazackerley** [comment]
see #155 about using state to check for falling to death.

I have also just tried using Falling.checkTriggered() to test for falling instead of that method that lists all the falling states. Falling.checkTriggered() returns false if there is a block below. When the rabbits are on the same square as the token, there is a block below, so checkTriggered says they are not falling and they gobble tokens.

There may be a neater way of doing this, but those don't work.

**Comment by andybalaam** [comment]
Hmm. See my comments on #155. If I get a chance soon to think properly about this and try some things out I will get back to you.If not I will merge this and come back to it. I think baddy rabbits will force us to find a cleaner system.

**Comment by andybalaam** [comment]
Merging since the behaviour is clearly correct and we can refactor the implementation later if we find a better way.

**Comment by colonelfazackerley** [comment]
I think it is valuable having a set of tests that cover situations that are bound to be awkward, however rabbit movement is coded.

I don't mind at all if the tests i have contributed are the only thing that survives a rewrite.

**Comment by andybalaam** [comment]
Couldn't agree more.

**Comment by andybalaam** [comment]
(As a general principle, not meaning that I want to throw away this code :-)

**Pull request merged**
