### PR TITLE
store CLI help in resource

### LINKED ISSUE #427: document ```./runrabbit -l foo.rel -s "bash;(2,3)"```
I think I forgot to do this.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
update help for solution command strings closes #427.

### CODE REVIEW

**Comment by andybalaam** [comment]
Wouldn't just Util.resourceLines() be enough? You don't want to load it from file - you always want it from the classpath.

**Comment by colonelfazackerley** [comment]
good point.

**Comment by colonelfazackerley** [comment]
argh

awry rebase or something

**Comment by colonelfazackerley** [comment]
now it's ready

**Pull request merged**
