### PR TITLE
cheat mode

### PR DESCRIPTION
**Pull request by colonelfazackerley**
- tap out the rhythm from Holst's Mars on the screen, where you drop tokens.
- complete a level
- all levels in that set are now available

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I made a small ogg with the rhythm needed. I can't upload it here...

Perhaps @andybalaam could put it on artificialworlds.net?

**Comment by andybalaam** [comment]
I like it. Remind me if I forget. We should probably have a note about this on the wiki.

**Comment by andybalaam** [comment]
I just finally got around to listening to the music to figure this out (I failed to get it right from the code).  When I tap out the rhythm in Easy 1 it prints Mars to the console, but even when I go out to the main menu and back in to Easy again I can only get into level 1.  Am I doing something wrong?

**Comment by tttppp** [comment]
I really like this idea as something which can be done in Swing and android. We may need a different cheat for the text UI? I was thinking maybe text adventure style:
```
> say "Mars"
```

**Comment by colonelfazackerley** [comment]
You have to complete a level in a set to get the menu to refresh, then the set becomes available.

Good idea, re text mode.

**Comment by andybalaam** [comment]
Documented here https://github.com/andybalaam/rabbit-escape/wiki/Tips-and-Tricks

**Pull request merged**
