### PR TITLE
From now on rabbots don't affect the out rabbit count

### PR DESCRIPTION
**Pull request by GamingInky**
That it

### CODE REVIEW

**Comment by andybalaam** [comment]
This needs a test before we can merge. I would also like to look into counting already-out rabbits in the initial count, but that is actually a totally different part of the cod.

**Comment by andybalaam** [comment]
I think there will be a revert step that also needs changing. Make sure the test covers reverting this change too.

**Comment by GamingInky** [comment]
Test: done
Revert step: done
Not repeating: done
Ready for another review!

**Comment by andybalaam** [comment]
Very cool, merged.

**Pull request merged**
