### PR TITLE
More cli

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not ready yet. i have a few more bits to add.

comments so far appreciated.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
this is ready

**Comment by andybalaam** [comment]
Can encoding or not be a property of the writing code but not the world? It feels a bit unclean that a world would know something about how it is written out.

**Comment by andybalaam** [comment]
In bash put quotes around e.g. `$@` (so making it `"$@"`) to support file paths containing spaces.

**Comment by colonelfazackerley** [comment]
I will see if I can make that work.

**Comment by colonelfazackerley** [comment]
anyone creating paths with spaces deserves what they get.

**Comment by colonelfazackerley** [comment]
That was a joke (mostly). I will try ```"$@"```.

**Comment by colonelfazackerley** [comment]
suggestions implemented and some rebasing. this is ready again.

**Comment by andybalaam** [comment]
Did the encoded writing reduce to almost nothing? Or did it somehow get rebased away?

**Comment by andybalaam** [comment]
Oh I think I see it. Excellent, thanks.

**Pull request merged**
