### PR TITLE
New Smallworld level: Uno.

### PR DESCRIPTION
**Pull request by tttppp**
This is 7x9, so I think it qualifies for Smallworld.

### CODE REVIEW

**Comment by tttppp** [comment]
When I thought about this during he night, I realised it's much easier than I intended. Maybe the bomb token should be moved to the bridge token, and the bridge token should be removed. Also the initial delay could be increased a bit.

**Comment by colonelfazackerley** [comment]
I have not tried this yet. Not all levels have to be hard...

**Comment by tttppp** [comment]
I improved the level. It has the same "one of each token" theme, but it's actually possible to go wrong now. I also managed to shrink the level in the process.

**Comment by colonelfazackerley** [comment]
After 10 min, I got 2 out. Yet to hit the target.

**Comment by andybalaam** [comment]
Good work focusing on small world. We need to complete a level set to have something worth releasing, and we are badly overdue for a release.

**Comment by colonelfazackerley** [comment]
We have a lot of new features to showcase. As soon as the overlay and water polygons are sorted, I will focus on levels and sets.

**Comment by andybalaam** [comment]
Woot. We need to test very thoroughly. I still need to figure out how I screwed up the configuration upgrade too :-(

**Comment by tttppp** [comment]
I think I should have put this in staging really, as it's got hints and a solution. Nevermind, someone can fix when they next add a small world level.

**Comment by colonelfazackerley** [comment]
i got 4 out

W=kSWk=~(USjk*}P]!WE(o(:(S~Oh~hSk@E#~~s}*f~}Eh](=~!jWh""S"hW["E~

i think 5 may be possible. i am not going to look at the official solutions quite yet.

**Comment by colonelfazackerley** [comment]
i retract that. i cant see how to get 5 out. i checked the official solution, and it is similar to mine.

**Comment by andybalaam** [comment]
Currently at https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/levels/staging/smallworld/Uno.rel

**Pull request merged**
