### PR TITLE
anim tester can dump frames to png

### LINKED ISSUE #224: Animation tester to make animated gifs
I can't capture decent ones because of the performance limitations of my linux running in a VirtualBox VM. So I have to switch to Windows to make them, and the software I am using there is rather annoying.

The animation tester (AT) already does things like applies offsets and displays scenery tiles, so it seems like a good place to make gifs.

If it's too much hassle in java to make an animated gif, the AT could produce frames and mencoder, ImageMagick or something could be used to stick the frames together.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
closes #224 

(wish i could do implements #blah).

at the moment F5 dumps 30 frames. i am thinking i should add F6 does a system call to ImageMagick's convert to make the animated gif, and F7 deletes the png frames. 

at the moment the frames and anim get put in the working directory. perhaps they should go in a subdir called tmp that we gitignore.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
this is higher quality than i can get in other ways.
- recording from the screen of my linux VM is limited by the frame rate the VM can manage
- the gif recorder I was using on win 7 could only do 8 fps and we need 10.

animation

**Comment by andybalaam** [comment]
Ideally the frames should go in ~/.rabbitescape/recordings/GENERATEDRANDOMNAME/frame1.png etc. I reckon?

**Comment by andybalaam** [comment]
This is really useful, thanks. Happy to merge now or wait for directory changes.

**Comment by colonelfazackerley** [comment]
wait a mo. I will do the dir change and do the ImageMagick call.

**Comment by colonelfazackerley** [comment]
ready

**Comment by colonelfazackerley** [comment]
and its ready ... now

**Comment by colonelfazackerley** [comment]
wait, i broke something

**Comment by colonelfazackerley** [comment]
slowtest is failing. trying to figure out what

**Comment by colonelfazackerley** [comment]
this is weird. slowtest fails when is plays hard 1 in text mode.but ``` ./runrabbit -l hard/level_01.rel -s1 ``` plays through fine.

**Comment by colonelfazackerley** [comment]
when i type in the solution used by the slowtest it works fine.

my setup just got slower, as i moved my working copy to a directory shared between host and guest. i think its a timing problem because file operations got slower.

i think it's fine.

**Comment by colonelfazackerley** [comment]
so, to conclude. please pull at your earliest convenience.

**Comment by colonelfazackerley** [comment]
rebased conflicts from whitespace thingy. ready again.

**Comment by andybalaam** [comment]
Brilliant, I want to try this soon. Do we now save into $HOME/.rabbitescape ? If so we no longer need to gitignore the recordings dir.

**Comment by colonelfazackerley** [comment]
It saves to './recordings', relative to the working directory. Perhaps this should be changed.

**Comment by andybalaam** [comment]
As a Dev tool maybe that's convenient, actually. Wouldn't be okay for installed software.

**Pull request merged**
