### PR TITLE
allow comments in rel files. lines starting '%' are ignored

### PR DESCRIPTION
**Pull request by colonelfazackerley**
```
// (C++) used in world ASCII art
/* (C) used in world ASCII art
# (bash) used in world ASCII art
% (GNU Octave alternate comment style) available
```

### CODE REVIEW

**Comment by tttppp** [comment]
Great stuff!

**Comment by andybalaam** [comment]
Brilliant - unit tests?  Further thoughts:

- annoying that we have closed avenues for more "normal" comment syntax.  We could use `;` which is a comment in Lisp I think, or `--` which is Haskell and Elm.  I wondered whether `:#` would work, as a special kind of `:` line, avoiding adding to the top-level namespace (which consists of `:` and "everything else") at the moment.  No reason to do any of this - just musing and wondering what you thought.

- would we like to extend this to allow comments anywhere on a line?

- do we want comments to survive a round-trip?  E.g. if we obfuscate a level by round-tripping it, would we still like the comments to be there

**Comment by colonelfazackerley** [comment]
The rel format is simple. I don't see the need to allow comments on the end of the line.

I like the simplicity of a single character, and I don't see a problem with adding to the top level namespace.

I am not a fan of ```;``` because it looks quite like ```:```.

I don't mind the comments being lost. Whatever makes things simpler. (Losing them may complicate test code)

A single ```-``` would be OK. I prefer ```%``` as I am used to using it as a comment marker.

**Comment by andybalaam** [comment]
Fair enough. Write a couple of unit tests and it's in.

**Comment by colonelfazackerley** [comment]
If something is used in some of the levels, then it is in the unit tests...

Apart from that I can't think what to test.

**Comment by colonelfazackerley** [comment]
Taking this view further, we may be able to remove some tests for other things that are in level files.

**Comment by colonelfazackerley** [comment]
Arguing against myself: the unit test Java files can be read as the specification. So all features should be described in them, to the maximum extent possible.

**Comment by tttppp** [comment]
The only rest I can think of for this is that there's no exception when loading a level with a comment. The level string should be as simple as is allowed to try to just test the one thing.

I think the tests that use the real level files are in theory testing that the levels are valid, where as the unit tests should be testing the code behaves as expected. (This is just a long winded way of agreeing with your second point).

Edit: Another potential test (scraping the barrel here) is that a % symbol can be used in e.g. a level name without stripping the rest of the line. Hmm, not sure about this one.

**Comment by colonelfazackerley** [comment]
The test checks
- comments are lost
- % in the name does not change the name.

**Comment by andybalaam** [comment]
> the unit test Java files can be read as the specification

Yes, definitely.  The names of tests should read like descriptions of behaviour.

> there's no exception when loading a level with a comment

Yes, and probably some minimal check that the lines before and after still work?

> the tests that use the real level files are in theory testing that the levels are valid

Yes, and although they are mixed in with our unit tests, they are really "component" or "system" tests that test a great swathe of behaviours, and therefore will fail if one of a large number of parts fail.  E.g. in this case, if the Makefile behaviour of generating "ls.txt" files fails, these tests will fail.

Highly specific unit tests serve to help track down where the problem lies when there is a failure, as well as serving as specification as you mentioned.

> that a % symbol can be used in e.g. a level name without stripping the rest of the line

Excellent test.  I don't mind whether `%` elsewhere is an error, or starts a comment, or is a normal character, and I don't mind changing our minds about this later, but I'd definitely like either a test pinning down the current intended behaviour, or a comment in the tests saying that it is deliberately unspecified.

**Comment by andybalaam** [comment]
Brilliant, thanks!

**Pull request merged**
