### PR TITLE
update gradle version to 2.1.0

### PR DESCRIPTION
**Pull request by colonelfazackerley**
i do wonder if just ignoring build.gradle would be a good idea.

studio has 2.1.0 on stable, and this comes with it.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I struggle to not commit this again along with something else. Makes the droid stuff more bothersome than it needs to be.

If you could consider this, that would be great. It's a one liner.

**Comment by andybalaam** [comment]
Does it rebuild if you delete it? In particular is there a command line route to get it back?

**Comment by colonelfazackerley** [comment]
Does the android code rebuild? delete what?

I dont understand the question.

**Comment by andybalaam** [comment]
If you delete build.gradle does it get recreated automatically?

**Pull request merged**
