### PR TITLE
Persist the amount of water in each cell.

### LINKED ISSUE #374: Bug: world with n's in
After trying to play a level on android with invisible water, this happens. I don't quite get it, but I think the problem is that level that is running can't round trip with the 'n' chars in.

```
03-27 08:19:06.241 26726-26726/? D/AndroidRuntime: Shutting down VM
03-27 08:19:06.243 26726-26726/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: net.artificialworlds.rabbitescape, PID: 26726
                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{net.artificialworlds.rabbitescape/rabbitescape.ui.android.AndroidGameActivity}: rabbitescape.engine.textworld.UnknownCharacter: Line number 25 contains an unknown character 'n' in text world lines:
                                                   :name=Aquifer
                                                   :description=Try not to drown.
                                                   :author_name=tttppp
                                                   :author_url=
                                                   :hint.1=a
                                                   :hint.2=b
                                                   :hint.3=
                                                   :hint.4=c
                                                   :solution.1=;dig;(19,4);2;bash;(18,7);dig;;block;3;(15,1);3;bash;dig;(17,7);(18,7);3;bash&bash;dig;(1,4);dig;block;;(4,1);4;bash;(2,7);3;dig&(3,7);105;dig;6;(9,2);2;block;2;(6,4);2;(15,4);;dig;2;(12,4);3;(9,6);(14,6);12;(6,4);;(6,6);10;(15,1);block;2;(16,4);4;block&bash;;(15,4);3;dig;;(10,6);8;block&bash;dig&(4,1);3;bash&(16,4);12
                                                   :num_rabbits=10
                                                   :num_to_save=5
                                                   :rabbit_delay=4
                                                   :num_saved=0
                                                   :num_killed=10
                                                   :num_waiting=0
                                                   :paused=false
                                                   :bash=20
                                                   :block=10
                                                   :dig=17
                                                   :explode=10
                                                   #####################
                                                   #         *         #
                                                   #  ###\       /###  #
                                                   #    ###########    #
                                                   #nnnnnnnnnnnNNNnnnnn#
                                                   #############N#######
                                                   #  #*NNNNNNN*NNN*#  #
                                                   #  ###############  #
                                                   #### #    O d  # ####
                                                        ###########     
                                                   :*=Q{Entrance.timeToNextRabbit:3}
                                                   :*=NP
                                                   :*=Nd
                                                   :*=NP
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                       at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:148)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                    Caused by: rabbitescape.engine.textworld.UnknownCharacter: Line number 25 contains an unknown character 'n' in text world lines:
                                                   :name=Aquifer
                                                   :description=Try not to drown.
                                                   :author_name=tttppp
                                                   :author_url=
                                                   :hint.1=a
                                                   :hint.2=b
                                                   :hint.3=
                                                   :hint.4=c
                                                   :solution.1=;dig;(19,4);2;bash;(18,7);dig;;block;3;(15,1);3;bash;dig;(17,7);(18,7);3;bash&bash;dig;(1,4);dig;block;;(4,1);4;bash;(2,7);3;dig&(3,7);105;dig;6;(9,2);2;block;2;(6,4);2;(15,4);;dig;2;(12,4);3;(9,6);(14,6);12;(6,4);;(6,6);10;(15,1);block;2;(16,4);4;block&bash;;(15,4);3;dig;;(10,6);8;block&bash;dig&(4,1);3;bash&(16,4);12
                                                   :num_rabbits=10
                                                   :num_to_save=5
                                                   :rabbit_delay=4
                                                   :num_saved=0
                                                   :num_killed=10
                                                   :num_waiting=0
                                                   :paused=false
                                                   :bash=20
                                                   :block=10
                                                   :dig=17
                                                   :explode=10
                                                   #####################
                                                   #         *         #
                                                   #  ###\       /###  #
                                                   #    ###########    #
                                                   #nnnnnnnnnnnNNNnnnnn#
                                                   #############N#######
                                                   #  #*NNNNNNN*NNN*#  #
                                                   #  ###############  #
                                                   #### #    O d  # ####
                                                        ###########     
                                                   :*=Q{Entrance.timeToNextRabbit:3}
                                                   :*=NP
                                                   :*=Nd
                                                   :*=NP
                                                       at rabbitescape.engine.textworld.LineProcessor.processChar(LineProcessor.java:622)
                                                       at rabbitescape.engine.textworld.LineProcessor.processItemsLine(LineProcessor.java:481)
                                                       at rabbitescape.engine.textworld.LineProcessor.process(LineProcessor.java:244)
                                                       at rabbitescape.engine.textworld.LineProcessor.<init>(LineProcessor.java:139)
                                                       at rabbitescape.engine.textworld.TextWorldManip.createWorldWithName(TextWorldManip.java:122)
                                                       at rabbitescape.engine.textworld.TextWorldManip.createWorld(TextWorldManip.java:102)
                                                       at rabbitescape.ui.android.AndroidGameActivity.loadWorld(AndroidGameActivity.java:119)
                                                       at rabbitescape.ui.android.AndroidGameActivity.onCreate(AndroidGameActivity.java:76)
                                                       at android.app.Activity.performCreate(Activity.java:6251)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
                                                       	... 10 more
```

### PR DESCRIPTION
**Pull request by tttppp**
This should fix #374. It also provides an implementation for #369.

The format for 100 units of persisted water at (1,4) is:
```
:n=1,4,100
```
If a cell is exactly half full or completely full then the symbol n or N is used instead.

### CODE REVIEW

**Comment by tttppp** [comment]
Before merging this we should have one more think about water in ramp cells, because I may have got it wrong. I'll have another look tomorrow.

**Comment by tttppp** [comment]
Resolved the issue with ramps. I think this is ready now.

**Comment by tttppp** [comment]
Once this is merged I've created a couple of water-based levels, the first of which uses standing water.

https://github.com/tttppp/rabbit-escape/tree/LevelForPersistWater

**Comment by andybalaam** [comment]
Seems nice and simple. Will read the code as soon as possible.

**Comment by andybalaam** [comment]
Brilliant.

**Comment by andybalaam** [comment]
Those tests with large lists of numeric water values are unfortunate. I think we need another option to the text rendering to exclude water amounts, similar to excluding changes and coords, and probably in tests we should default to not checking exact water amounts, and have a couple of special tests that do check them.

**Comment by tttppp** [comment]
Sounds like a good idea!

**Pull request merged**
