### PR TITLE
New level Sloping Off.

### PR DESCRIPTION
**Pull request by tttppp**
Also move Uno to staging.

### CODE REVIEW

**Comment by tttppp** [comment]
An easy one.

**Comment by colonelfazackerley** [comment]
I liked it it has novel puzzle elements.

"L}i}RP3!RPldmR}il= 3^}^}RP|mg} !^}&!g=m!Rl l}=i^L3^*i})}m"<}"g},xi}

I think it needs an explode token.

**Comment by colonelfazackerley** [comment]
My solution above is different to yours. Mine relies on the fact that tokens dropped first are picked up first.

**Comment by tttppp** [comment]
It was inspired by the conversations about rabbit ordering that we had. The level would be much easier if the right hand rabbits picked up tokens before the left.

**Comment by tttppp** [comment]
I updated it to make it marginally harder by adding a couple more rabbits and another floater token. Your solution still works, but is slightly trickier! :-)  I also added an explode token, because that can be a satisfying way to get rid of the last rabbit.

**Comment by tttppp** [comment]
I can't see any way to save all ten, but that would make a nice Deja Vu level if it's possible.

**Pull request merged**
