### PR TITLE
Refactor block type into block material and block shape.

### PR DESCRIPTION
**Pull request by tttppp**
This is to prepare for blocks having a capacity of water they can hold (i.e. determined by shape).

### CODE REVIEW

**Comment by andybalaam** [comment]
Superb. Metal bridges anyone?

**Comment by andybalaam** [comment]
Why are the enum values SHOUTING?

**Comment by tttppp** [comment]
Enums always SHOUT! Apparently it's because they're constants: https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

Maybe bridges should be sponge, or something porous, as I was planning for bridges to let water pass straight through. Probably best to have as a future enhancement though, as separate water regions in a single cell is making my brain ache!

**Comment by colonelfazackerley** [comment]
Wooden blocks for burning...

Good work

**Comment by colonelfazackerley** [comment]
I see, so in languages that use a preprocessor, it would be confusing to use SHOUTING for anything else.

[ducks]

**Pull request merged**
