### PR TITLE
custom animation and sound for drowning

### PR DESCRIPTION
**Pull request by colonelfazackerley**

### CODE REVIEW

**Comment by andybalaam** [comment]
Any chance of a screen shot?

**Comment by colonelfazackerley** [comment]
Of course.

re

**Comment by andybalaam** [comment]
Awesome!  Wondering whether the sound needs to be higher-pitched.  Will compare with others and maybe make a pull request for you to look at.

**Comment by andybalaam** [comment]
Possible drowning sound (that I'm not particularly happy with) is in #385

**Comment by andybalaam** [comment]
@colonelfazackerley I had to fix a couple of broken tests.  On the plus side I made the failure message better in the process :-)

**Pull request merged**
