### PR TITLE
Level: Under pressure

### PR DESCRIPTION
**Pull request by colonelfazackerley**
Look at me: new level by pull req.

I think it's tricky. I am keen to find out if I missed a trivial solution.

### CODE REVIEW

**Comment by andybalaam** [comment]
I will make a snapshot when I get a chance

**Comment by tttppp** [comment]
This seems to cause the tests to fail:

```
Testcase: All_staging_levels_work_and_have_winning_solutions took 0.206 sec
    [junit] 	Caused an ERROR
    [junit] Solution failed: ability 'bash' was used when there were none left at command 28 of solution 1 in smallworld/Under-pressure
```

I assume it was due to https://github.com/andybalaam/rabbit-escape/issues/414 (which is now fixed).

Also I saved 9, is that better than intended?

```
[y#y7$CKgIO|}ggOVy#yy}[IOh'%y[Cy#jOp7yfV#T'CA7AyO~C|IgyzT#yppgOyCK7A%O|}'CpyCy%yy}Op'_gTp#CgKI*O#yyKO#OCVyyf7y'V%yf#CAygy7#y#pCpCIjy#p7py%O~}Ty%7f'~Tj}
```

**Comment by colonelfazackerley** [comment]
yes, your solution is better than mine. it is not simple, though, so I don't mind. 

i suggest leaving 8 as the target and keeping 9 in mind for deja vu.

**Comment by andybalaam** [comment]
#87 deja vu

**Pull request merged**
