### PR TITLE
ignore android studio project files

### PR DESCRIPTION
**Pull request by colonelfazackerley**
i had to 'git rm' some files before this worked. android studio worked OK after this.

### CODE REVIEW

**Comment by andybalaam** [comment]
Are you sure ignoring build.gradle is ok? It looks like it won't change to often. ..

**Comment by colonelfazackerley** [comment]
I did rm build.gradle, and it came back fine. if you check the diff in #318, you can see it's just this
```diff
-        classpath 'com.android.tools.build:gradle:1.0.0-rc2'
+        classpath 'com.android.tools.build:gradle:1.5.0'
```
perhaps you can upgrade to 1.5.0, and there will be no changes to the file? then we dont need to gitignore it.

**Comment by andybalaam** [comment]
Let's try that and if it becomes too annoying we will ignore it.

**Comment by andybalaam** [comment]
I think I have addressed this. Reopen if not.

**Pull request closed without merging**
