### PR TITLE
Outdoors solutions for levels 1, 2 and 3.

### PR DESCRIPTION
**Pull request by tttppp**
I'm not sure when I'll next get chance to work on this, so here are three solutions for outdoors levels.  Saw (level 2) is significantly harder than I remembered - I think this is due to the changes in behaviour since it was written.

### CODE REVIEW

**Comment by andybalaam** [comment]
Great,  thanks

**Comment by andybalaam** [comment]
What happened to Saw? Do we need to reorder it?

**Comment by colonelfazackerley** [comment]
I don't think the changes have made Saw harder. Perhaps a case of memory being a funny thing?

**Comment by andybalaam** [comment]
I just tried it and the rabbits no longer enter the exit ( because they fall instead). I think I regard this as a bug in the level. Opinions?

**Comment by colonelfazackerley** [comment]
Yup, I will tweak the level.

I will retract "Perhaps a case of memory being a funny thing".

This is why we need solutions for all levels.

**Comment by tttppp** [comment]
I think the fact that it's still soluble means it's fine, but maybe not quite the level that the author intended.

**Comment by andybalaam** [comment]
> This is why we need solutions for all levels.

Totally agree.

**Comment by andybalaam** [comment]
> I think the fact that it's still soluble means it's fine

I think it's too hard for this order. Candidate for a deja vu level?

**Pull request merged**
