### PR TITLE
store void style in World. generate reproducible styles based on worl…

### PR DESCRIPTION
**Pull request by colonelfazackerley**
…d names

I think this should address #303

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I am just going to tweak so you dont need shouty caps in the rel to declare the style.

**Comment by colonelfazackerley** [comment]
and implement the TODO.

ready to merge, i think.

**Comment by andybalaam** [comment]
Excellent. I really feel like you're starting to code in my style. This may not be a good thing :-). 2 suggestions:
1. You can use name.hashCode or even name.length to get a hash of the name to choose a consistent void,  but if you prefer it how it is I'm ok with it. 
2. I'm pretty sure there's a join function in Utils that can make the list of styles for the exception. 
Happy to merge now or wait for updates.

**Comment by colonelfazackerley** [comment]
I can be taught to perform simple tasks.

Java spec says
>  Whenever it is invoked on the same object more than once during an execution of a Java application, the hashCode method must consistently return the same integer, provided no information used in equals comparisons on the object is modified. This integer need not remain consistent from one execution of an application to another execution of the same application.
 
I would like the same void style after a program restart.

Also, for short names and increasing numbers of styles name.length may not cut it. Lets stick with my homebrew hash.

**Comment by colonelfazackerley** [comment]
There was not quite the right join, but there is now. Good point.

I think this is OK to merge.

>  I really feel like you're starting to code in my style

I am sure I will make your eyes bleed again soon.

**Comment by andybalaam** [comment]
Good point about hashCode. I'd prefer the home made hash to be a separate function. Please can we have a unit test for the new Util (which is great by the way)

**Pull request merged**
