### PR TITLE
do not save dimension before frame is active. fixes #117

### LINKED ISSUE #117: Bug: window loses width
```bash
cf@re:~/re/rabbit-escape$ cat ~/.rabbitescape/config/ui.properties | grep game.window.width
game.window.width=775
cf@re:~/re/rabbit-escape$ make rungui 
<snip>
cf@re:~/re/rabbit-escape$ cat ~/.rabbitescape/config/ui.properties | grep game.window.width
game.window.width=767
cf@re:~/re/rabbit-escape$ make rungui 
<snip>
cf@re:~/re/rabbit-escape$ cat ~/.rabbitescape/config/ui.properties | grep game.window.width
game.window.width=759
```

Starting and closing the window loses 8 pixels.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
reasonably principled fix.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I have no idea why the makefile appears in this diff.

**Comment by tttppp** [comment]
The file is called null, so I guess you accidentally redirected a command to null, rather than /dev/null? You can safely "git rm" it.

**Comment by colonelfazackerley** [comment]
That explains it. I am blonde you know....

I will fix this and rebase later.

**Comment by colonelfazackerley** [comment]
rebased, optimised, primed and chomping.

**Comment by andybalaam** [comment]
Beautiful

**Pull request merged**
