### PR TITLE
runrabbit text solution player accepts solution strings (coded or not…

### PR DESCRIPTION
**Pull request by colonelfazackerley**
…) as well as solution number

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
On second thoughts. don't merge yet. I want to make this work on swing too.

**Comment by andybalaam** [comment]
I'd prefer if the solution string came from a different named argument instead of two possible formats for the same argument. But I will merge like this if you want. 

This could do with an update to the docs too.

**Comment by colonelfazackerley** [comment]
I like using single letter abbreviations for the command line arguments. We will run out of letters if we have too many. This would be 3 (solution index, command string and obfuscated command string).

What's wrong with having different formats if they can be differentiated?

Please merge.

**Comment by andybalaam** [comment]
> What's wrong with having different formats if they can be differentiated?

The only rational argument I can come up with is if you accidentally type "1q" when you meant "1" you would get a confusing error message.

**Comment by colonelfazackerley** [comment]
I can change it, if there is a problem.

**Comment by andybalaam** [comment]
Very minor thing

**Pull request merged**
