### PR TITLE
save brolly state

### LINKED ISSUE #405: bug: brollychuting ability lost when screen turned on android
I have not tried this, but from looking at the code, I am fairly sure we have this problem.

I think the solution playing test code should be saving and restoring state so we find these issues.

### PR DESCRIPTION
**Pull request by colonelfazackerley**
…lychuting ability state. fixes #405

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I had a rethink.

the "inter-behaviour refs are not saved with state. remove them. " bit is rubbish. I need to rebase it away.

**Comment by colonelfazackerley** [comment]
done.

ready.

**Comment by andybalaam** [comment]
Please can we have at least one test that failed before and passes now?

**Comment by colonelfazackerley** [comment]
At HEAD all tests pass. If you then
```bash
git co 4366d71 rabbit-escape-engine/src/rabbitescape/engine/behaviours/Brollychuting.java
 ```
the new test fails.

**Comment by andybalaam** [comment]
Perfect, thanks

**Pull request merged**
