### PR TITLE
Text runner cli

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not ready yet.

working on command line util ATM.

i intend to write code that will print the world in all steps while it runs a solution.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
this is ready

**Comment by andybalaam** [comment]
You could unit test the solution runner changes if you passed in System.out as an argument.

**Comment by andybalaam** [comment]
But generally awesome

**Comment by andybalaam** [comment]
Usual convention for long options with parameter attached is `--option=param`

**Comment by colonelfazackerley** [comment]
OK i will make the changes. don't pull quite yet.

**Comment by colonelfazackerley** [comment]
Stream thingy and = whotsit done.

ready again.

**Comment by andybalaam** [comment]
Very cool. To translate exceptions into English add a line to https://github.com/andybalaam/rabbit-escape/blob/master/rabbit-escape-engine/src/rabbitescape/engine/err/exceptions_en.properties

**Pull request merged**
