### PR TITLE
bash script to launch swing or text ui

### PR DESCRIPTION
**Pull request by colonelfazackerley**
i would like to combine the mains, so we have a single text main() and a single swing main(). the arg parsing would be done in java. that's the next step.

### CODE REVIEW

**Comment by andybalaam** [comment]
Excellent. I suggest `--help` just because it's standard, and I suggest the script be called `rabbitescape` but am open to persuasion on both counts.

**Comment by andybalaam** [comment]
I also agree with your next steps.

**Comment by colonelfazackerley** [comment]
I am fine with --help (and alternatively -h). runrabbit amuses me...

**Comment by andybalaam** [comment]
I thought it might.

**Pull request merged**
