### PR TITLE
custom frames for fire being extinguished by water

### PR DESCRIPTION
**Pull request by colonelfazackerley**
I hope @tttppp will not be offended if I prefer this.

### CODE REVIEW

**Comment by tttppp** [comment]
I haven't seen what you've done, but all my animations were meant to be temporary.

**Comment by andybalaam** [comment]
Any chance of a gif?

**Comment by colonelfazackerley** [comment]
re

**Comment by tttppp** [comment]
Looks good to me!

**Comment by andybalaam** [comment]
Really cool.

**Pull request merged**
