### PR TITLE
Anim keys

### PR DESCRIPTION
**Pull request by colonelfazackerley**
This is not quite ready yet. I thought I would post this so everyone knows what I am working on.

I intend to add features
- step a frame back and forth with keystrokes
- toggle a mode on/off where it prints the names of the frames as it renders them.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
bugger, i meant to branch from master, not my anim slope branch. i guess this wont matter if the anim slope branch is merged.

**Comment by colonelfazackerley** [comment]
I rebased away that woops.

**Comment by colonelfazackerley** [comment]
ready for merging

**Comment by andybalaam** [comment]
A or D could automatically flip you into step mode.

**Comment by andybalaam** [comment]
Very good, ta.

**Pull request merged**
