### PR TITLE
Tac overlay

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not quite ready. see #399

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
I think this is ready.

Please review/merge.

**Comment by andybalaam** [comment]
Sorry, this needs a rebase

**Comment by andybalaam** [comment]
Sorry, this needs a rebase

**Comment by colonelfazackerley** [comment]
This is ready

**Comment by andybalaam** [comment]
We need some more rendering options for tests to exclude water numbers and rabbit indices. I am somewhat unhappy with every rabbit being a * in Android saved levels but I guess I can live with it.

**Pull request merged**
