### PR TITLE
Brolly

### PR DESCRIPTION
**Pull request by colonelfazackerley**
not ready yet.

### CODE REVIEW

**Comment by colonelfazackerley** [comment]
this is ready

**Comment by colonelfazackerley** [comment]
no it's not

**Comment by colonelfazackerley** [comment]
ready again

**Comment by colonelfazackerley** [comment]
```
:name=brolly intro
:brolly=2
:bridge=1
:dig=1
:block=1
:explode=1
:climb=1
:rabbit_delay=13,13,5
:num_rabbits=5
:num_to_save=5
Q        
         
#####    
#####    
#####    
#####    
#####   O
#########
```
I think brolly use is essential to complete this.

**Comment by colonelfazackerley** [comment]
Not done it, but I think there is a non brolly solution.

**Comment by colonelfazackerley** [comment]
Let me know if you dont like the static config access stuff in "config option to print rabbit states"

Suggest a better way of getting the IConfig available in Rabbit.

**Comment by colonelfazackerley** [comment]
I found a bug for brollychuting+climbing. just looking into it.

**Comment by colonelfazackerley** [comment]
A better intro to brollies level.

```
:name=Brollychuting 101
:brolly=1
:bridge=1
:climb=1
:rabbit_delay=23,1
:num_rabbits=5
:num_to_save=5
Q##########
          O
####   ####
####   ####
###    ####
####   ####
####   ####
####   ####
###########

```

**Comment by colonelfazackerley** [comment]
new version of my first brolly intro level
```
:name=Brolly descent
:brolly=2
:bridge=1
:block=1
:explode=1
:climb=1
:rabbit_delay=13,13,5
:num_rabbits=5
:num_to_save=5
Q        

####     
####     
####     
####     
####    O
#########
```

**Comment by colonelfazackerley** [comment]
a third brolly level
```
:name=The great divide
:num_rabbits=3
:climb=1
:brolly=1
:bridge=2
:bash=2
 O         
##   #   ##
#Q   #    #
#    #    #
#    #    #
#    #    #
#    #    #
###########
```

**Comment by tttppp** [comment]
The third one looks hard. I think I can see the solutions to the other two. Looking forward to trying them!

**Comment by colonelfazackerley** [comment]
I will post a link to a jar of my branch soon, if andy does not.

probably better on his server than my google drive.

**Comment by andybalaam** [comment]
I've not had a chance to read the code or try it yet, but I made a snapshot (0.7.0.4-brolly) and put it up here: http://artificialworlds.net/rabbit-escape/snapshots/

**Comment by tttppp** [comment]
Hmm, well it works on my phone, but it doesn't allow me access to any brolly levels.  Copy/paste level loading on Android would be nice at some point (or network loading with internet permission - shudder).

**Comment by colonelfazackerley** [comment]
how bad is the overhead for extra google play entries?

we could have a rabbit-escape-dev version that has extra permissions.

**Comment by tttppp** [comment]
Crashed this on Android by starting level 14 hard and waiting for the first rabbit to walk. I don't have a crash report at the moment, but I'm going to downgrade to pre-brolly.

**Comment by colonelfazackerley** [comment]
i tried the brolly branch with swing on linux and win. hard 14 was fine.

i suspect your crash was not related to my changes.

**Comment by tttppp** [comment]
After installing a lower version over the top I still had the same problem, so I've reinstalled from scratch. I'm not sure it's related either, as I seemed to be able to play normally when I first installed. I wondered if your branch doesn't have Andy's fixes in?

**Comment by colonelfazackerley** [comment]
I am missing several of his commits from dec 24th on. That is likely.

**Comment by colonelfazackerley** [comment]
Adding "num_to_save". This may be possible without brollies.

```
:name=The great divide
:num_rabbits=3
:num_to_save=3
:climb=1
:brolly=1
:bridge=2
:bash=2
 O         
##   #   ##
#Q   #    #
#    #    #
#    #    #
#    #    #
#    #    #
###########
```

**Comment by colonelfazackerley** [comment]
It is possible without any brollies. I will have to work on that.

**Comment by andybalaam** [comment]
Yes the brolly version does not have all the fixes in 0.7.1. If you crash 0.7.1 or later i am very interested.

**Comment by colonelfazackerley** [comment]
a #241 candidate brolly level
```
:name=Brolly hero
:description=
:author_name=
:author_url=
:solution.1.code=4|x%%e%<$u4?J%9B"AQM%M?A4o5ZweE%Jx]4]A%]#h^##%BeAa@#]&e
:num_rabbits=2
:num_to_save=2
:rabbit_delay=4
:num_saved=0
:num_killed=0
:num_waiting=2
:paused=false
:brolly=1
:dig=2
:explode=1
##   ##
#c/#\j#
###p###
#  # Q#
#     #
#     #
#  #  #
#O #  #
#######
```

**Comment by andybalaam** [comment]
I am getting around to reviewing this but I need to do it on a real computer so will take longer. Looks awesome.

**Comment by andybalaam** [comment]
This is indeed awesome.  I am pulling and then will fight the static config.

**Comment by andybalaam** [comment]
> Let me know if you dont like the static config access stuff in "config option to print rabbit states"
> Suggest a better way of getting the IConfig available in Rabbit.

See 58fdb35664fd8e9a0e247f33c7589e39163ee0dc - I used a combination of [Parameterise from Above](http://accu.org/index.php/journals/1411) and pulling the logging out as far as I could from the core logic.

Limitations of my approach:

- Only works in Swing UI, but I think that was true already?
- Required me to make World available through Physics, but I don't feel too bad about that.

Advantages of my approach

- Does not make my eyes bleed

**Comment by andybalaam** [comment]
Now I think the levels should be split out into separate issues.

**Pull request merged**
