### PR TITLE
blue shine to the metal blocks

### PR DESCRIPTION
**Pull request by colonelfazackerley**
binary files needed merging. easier to make a new branch.

### CODE REVIEW

**Comment by andybalaam** [comment]
Brilliant,  thanks

**Comment by colonelfazackerley** [comment]
I managed to recover the gimp .xcf source for these images from my non-booting VM by mounting the vmdk.

Where did you want them? I will make a pull request.

**Comment by colonelfazackerley** [comment]
found the answer here #323

**Comment by andybalaam** [comment]
Sorry - feel free to ping me again if I am slow to respond. I am not finding a lot of time at the moment but should at least be up to date with answering quick questions.

**Pull request merged**
